# Generated by Django 5.0.6 on 2025-04-09 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seatdetection',
            name='backend_app_month_c69487_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatdetection',
            name='backend_app_seat_id_3004e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatdetection',
            name='backend_app_time_st_156db8_idx',
        ),
    ]
