# Generated by Django 5.0.6 on 2025-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
