# Generated by Django 5.0.6 on 2025-05-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_camera_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatdetection',
            name='centroid_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatdetection',
            name='centroid_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
