# Generated by Django 5.0.6 on 2025-04-20 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_remove_seatdetection_backend_app_month_c69487_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('track_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyEntrySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_block', models.DateTimeField(unique=True)),
                ('entered', models.PositiveIntegerField(default=0)),
                ('exited', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='seatdetection',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='seatdetection',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='seatdetection',
            name='month',
        ),
        migrations.RemoveField(
            model_name='seatdetection',
            name='seat',
        ),
        migrations.AddField(
            model_name='seatdetection',
            name='chair_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
