# Generated by Django 5.0.6 on 2025-05-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_seatdetection_centroid_x_seatdetection_centroid_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatdetection',
            name='zone_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
