# Generated by Django 5.0.6 on 2025-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_entryevent_hourlyentrysummary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('seating', 'Seating'), ('entry', 'Entry'), ('exit', 'Exit')], default='seating', max_length=20),
        ),
    ]
