# Generated by Django 5.0.6 on 2025-05-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_seatdetection_zone_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatdetection',
            name='zone_id',
        ),
    ]
