# Generated by Django 5.0.6 on 2025-04-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_remove_activitylog_action_activitylog_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatdetection',
            name='camera',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='backend_app.camera'),
            preserve_default=False,
        ),
    ]
