# Generated by Django 5.0.6 on 2025-04-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_seatdetection_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='face_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entryevent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.customer'),
        ),
    ]
