# Generated by Django 5.0.6 on 2025-05-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_remove_seatdetection_zone_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('cafe', 'seat_id')},
        ),
    ]
