# Generated by Django 5.0.6 on 2025-04-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_customer_face_id_entryevent_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='backend_app.usercafe'),
            preserve_default=False,
        ),
    ]
