# Generated by Django 5.0.6 on 2025-04-23 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_customer_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryevent',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.camera'),
        ),
    ]
