# Generated by Django 5.0.6 on 2025-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_seat_chair_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('cafe', 'chair_index')},
        ),
    ]
