# Generated by Django 5.0.6 on 2025-05-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_alter_floor_name_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('cafe', 'seat_id')},
        ),
    ]
