# Generated by Django 5.0.6 on 2025-04-24 07:16

from django.db import migrations, models
import datetime
from django.utils.timezone import now
...
now = now()

def set_default_created_at(apps, schema_editor):
    Report = apps.get_model('backend_app', 'Report')
    Report.objects.filter(created_at__isnull=True).update(created_at=now())

class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_entryevent_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='peak_customer',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='report',
            name='peak_hour',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='returning_customer',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),  # Use auto_now_add without a default
        ),
        migrations.AddField(
            model_name='report',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.IntegerField(),  # Remove default value and require explicit assignment
        ),
        migrations.RunPython(set_default_created_at),  # Set a default value for the existing records
    ]
