# Generated by Django 5.0.6 on 2025-05-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_rename_peak_customer_report_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('cafe', 'year', 'month')},
        ),
    ]
